### ISSUE TITLE
Dark Matter now makes the server icons bigger?

### ISSUE THREAD

**Issue by AneiDoru** [cosmicsalad/Discord-Themes-and-Plugins#45]
This just happened today and I can't fix it, what's going on?
![iconsbig](https://user-images.githubusercontent.com/25395094/41688094-7a998888-749f-11e8-8d09-cf5d62d00df4.png)

**Comment by AneiDoru** [comment]
By the way I took the custom CSS that makes the server list two rows off and it still did it.

**Comment by integralfx** [comment]
Try adding this
```css
/* Server Icons */
.iconSizeLarge-161qtT {
    height: 40px;
    width: 40px;
}
```
