### ISSUE TITLE
Dark matters makes the server list now the normal discord theme?

### ISSUE THREAD

**Issue by level-04** [cosmicsalad/Discord-Themes-and-Plugins#46]
![knipsel](https://user-images.githubusercontent.com/41976536/43495917-e20813ac-953a-11e8-87c4-97d6eddf1fdb.PNG)
This really distracts me and i also noticed that the circles that the icons are in are also bigger then the normal dark matters, but that is probably just how the normal discord theme looks like. Does anyone have a fix for this?

**Comment by integralfx** [comment]
```css
.guildsWrapper-5TJh6A {
    background: rgba(0,0,0,0.6) !important;
}
```

Play around with the last value to find the one that works best for you.

You can fix the theme by using inspector (Ctrl Shift I), when it breaks.
