### ISSUE TITLE
Dark matters now makes the chat box the normal theme

### ISSUE THREAD

**Issue by level-04** [cosmicsalad/Discord-Themes-and-Plugins#47]
https://cdn.discordapp.com/attachments/334077784953716736/475278392728616960/unknown.png
I don't know if this becomes a trend or?

**Comment by integralfx** [comment]
With every Discord update, the class names change.

I can't remember if this fully fixes it, but give it a try.
```css
[class^="chat"] [class^="messagesWrapper"],
[class^="chat"] form {
	background-color: transparent;
}
```

This should work with future Discord updates.
